### ISSUE TITLE
Loss does not decrease while training

### ISSUE THREAD

**Issue by fby1221** [KKKSQJ/DeepLearning#1]
Hi，thanks a lot for publishing the code. I had a question: I use your code  to train CUB_200_2011datasets, but loss does not decrease while training

**Comment by KKKSQJ** [comment]
Hi, thanks for your issue. I found a bug in models/transfg.py. Now, I have fixed this bug. The model can be trained normally, I will upload my configuration file and training log

**Comment by KKKSQJ** [comment]
> Hi，thanks a lot for publishing the code. I had a question: I use your code to train CUB_200_2011datasets, but loss does not decrease while training

Hi, thanks for your issue. I found a bug in models/transfg.py. Now, I have fixed this bug. The model can be trained normally, I will upload my configuration file and training log
