### ISSUE TITLE
TransFG on stcar dataset

### ISSUE THREAD

**Issue by XDhyao** [KKKSQJ/DeepLearning#2]
你好，请问你们是否尝试过在斯坦福汽车数据集上测试代码，我用源码跑下来效果一直很差，比论文中的效果低3%左右

**Comment by KKKSQJ** [comment]
你好。我并没有测试过Stanford Cars数据集。不过我测试了CUB-200-2011数据集。实际情况比论文中的精度低1.7%左右。您可以在https://github.com/KKKSQJ/DeepLearning/tree/master/classification/TransFG/logs/TransFG_CUB查看训练日志
