### ISSUE TITLE
GPU指定

### ISSUE THREAD

**Issue by zhonglin516** [KKKSQJ/DeepLearning#4]
使用vggnet，有多块GPU怎么指定具体某一块？

**Comment by KKKSQJ** [comment]
有两种方法：
1. 在命令行中使用 export CUDA_VISIBLE_DEVICES=0 来指定GPU。
例如：
export CUDA_VISIBLE_DEVICES=0 python test.py
# 表示运行test.py文件时，使用编号为0的GPU卡
export CUDA_VISIBLE_DEVICES=0,2 python test.py
# 表示运行test.py文件时，使用编号为0和2的GPU卡

2.在脚本中添加 os.environ["CUDA_VISIBLE_DEVICES"] = "0"
例如：
import os
# 使用第一张与第三张GPU卡
os.environ["CUDA_VISIBLE_DEVICES"] = "0, 2"
