### ISSUE TITLE
关于用IP102数据集训练遇到的问题

### ISSUE THREAD

**Issue by Aoshika123** [KKKSQJ/DeepLearning#5]
您好作者，我在用TransFG跑IP102数据集的时候，在训练阶段loss一直保持在4点多不变，Valid Accuracy只有百分之0.4，经过多轮训练一直不变化，请问您有遇到过这类的问题么？

**Comment by KKKSQJ** [comment]
您好，我没有试过训练IP102数据集。您可以自己定义数据集的读取方式以适应您的数据集，并且确保您的数据、参数配置等信息正确。您可以在https://github.com/KKKSQJ/DeepLearning/tree/master/classification/TransFG/logs  找到我训练CUB200数据集的全部配置信息以及log日志。
